const NOTIFICATION_TYPES = {
  ORDER_PLACED: "ORDER_PLACED",

  ORDER_ACCEPTED: "ORDER_ACCEPTED",

  ORDER_PREPARING: "ORDER_PREPARING",

  ORDER_OUT_FOR_DELIVERY: "ORDER_OUT_FOR_DELIVERY",

  ORDER_DELIVERED: "ORDER_DELIVERED",

  ORDER_CANCELLED: "ORDER_CANCELLED",

  FARMER_APPROVED: "FARMER_APPROVED",

  FARMER_REJECTED: "FARMER_REJECTED",

  ADMIN_ALERT: "ADMIN_ALERT",
};

export default NOTIFICATION_TYPES;